### ISSUE TITLE
Add to cart button

### ISSUE THREAD

**Issue by darshi-shah** [darshi-shah/inkshop#2]
After adding a product to the cart, the add to cart button disappears until the page is reloaded for some products (Südlink 177 - September 2016 for example). If you have any ideas why that could be, let me know.

**Comment by darshi-shah** [comment]
Hi Rainer,

The issue is with showing products twice on home page:  once in main listing and second time in latest products in second sidebar. If I remove latest products from sidebar, add to cart works as expected.

Please see https://www.drupal.org/node/2357855. I tried with mentioned code but that doesnt help.

Please let me know if I should continue with this. I have used 2 hours in it.

Thanks
Darshi

**Comment by heliogabal** [comment]
Hi Darshi, 

good find! Then I will just deactivate the latest product block for now. The product list shows the newest products on top with a badge anyway, so this should be enough. Now, there is just some empty space to the right, I'll see how I'll fill that later. Thanks!
